on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check fmt
        run: |
          make fmt
          git diff --exit-code
      - run: make test
